### ISSUE TITLE
No async api functions

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/fingerprinting-blocking-methods-study-addon#18]
https://github.com/mozilla/fingerprinting-blocking-methods-study-addon/blob/64d5f204363d3724cec2c96d889e4160083064fb/src/common/privileged/fpPrefs/api.js#L22

No need to use async in the api functions (e.g. `async isFpProtectionEnabled()`) since none of them use await.

**Comment by birdsarah** [comment]
I have made this change. However, the thing that confused me is that these functions return a Promise. If I'm understanding our slack chat correctly it's because they're mediated through the ExtensionAPI. Here's the snippet from our slack conversation:

me: The privileged schema.json and api.js - should those functions be async? I would assume not based on your comment, but I was basing my work on code samples such as https://github.com/mozilla/federated-learning-v2-study-addon/blob/master/src/privileged/frecencyPrefs/api.js which are async functions. But if the code within them isn't async then why would the ExtensionAPI code be async?

mixedpuppy: They will essentially be async no matter what at that level.  But the js implementation doesn't need async.  Leave schema as async: true, because you'd have to do special stuff if you tried false.  But the js itself should only use async if you need it in js. The only time the extension wouldn't get a promise is when you use async: false in schema.  But I don't think that works in experimental apis, it will always be async: true. none of this api has anythign that will result in an actual wait
nothing in nsIPrefBranch is async

I understand what you're saying, and I've left it as you've requested it, but it tripped me up along the way and I'd just like to note that not marking the functions in api.js as async functions added confusion for me.

@rhelmer @mythmon @bdanforth - just food for thought as we continue to build out guidelines.

**Comment by mixedpuppy** [comment]
@birdsarah if the js itself does not need async functionality the function doesn't need to be decorated with async.

The internals of the extension architecture will wrap calls, extensions are not calling these directly.  It's probably not necessary to have async in the schema at all for these api calls, however, it will likely be an async operation anyway since the api is in the parent process (ie. addon_parent in the manifest).  Generally if you want a completely synchronous function, you'd have to implement it in the child process.

**Comment by birdsarah** [comment]
> @birdsarah if the js itself does not need async functionality the function doesn't need to be decorated with async.

Just to reiterate. I understand that. That's not the point I'm making. Technical correctness and intuitiveness do not necessarily go hand in hand.
